/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Demo2;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author minhdq
 */
public final class DN extends javax.swing.JFrame {

    /**
     * Creates new form DN
     */
    ArrayList<SinhVien> listSV = new ArrayList<>();

    public DN() {
        initComponents();
        setLocationRelativeTo(null);// show form ra giữa màn hình
        setResizable(false);// ko cho thay đổi kích cỡ form
        rdNam.setSelected(true);
        cbLuuThongTin.setSelected(true);
        loadData();
        cbbSinhVien.removeAllItems();// xóa dữ liệu cũ trên cbb
        for (SinhVien xxx : listSV) {
            cbbSinhVien.addItem(xxx.getUserName());
        }
        fillTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tfPassWord = new javax.swing.JPasswordField();
        btn_DangNhap = new javax.swing.JButton();
        btn_LamMoi = new javax.swing.JButton();
        btn_SieuThoat = new javax.swing.JButton();
        lbDangNhap = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfUserName = new javax.swing.JTextField();
        cbbSinhVien = new javax.swing.JComboBox<>();
        btnShow = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        lbShowPass = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbShowAcc = new javax.swing.JTable();
        btFillTable = new javax.swing.JButton();
        cbLuuThongTin = new javax.swing.JCheckBox();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        btShowGender = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_DangNhap.setText("Đăng Nhập");
        btn_DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangNhapActionPerformed(evt);
            }
        });

        btn_LamMoi.setText("Làm mới");
        btn_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiActionPerformed(evt);
            }
        });

        btn_SieuThoat.setText("Siêu Thoát");
        btn_SieuThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SieuThoatActionPerformed(evt);
            }
        });

        lbDangNhap.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lbDangNhap.setForeground(new java.awt.Color(0, 51, 255));
        lbDangNhap.setText("Đăng Nhập");
        lbDangNhap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Username: ");

        jLabel3.setText("Password: ");

        cbbSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbSinhVienMouseClicked(evt);
            }
        });
        cbbSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSinhVienActionPerformed(evt);
            }
        });

        btnShow.setText("Show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        tbShowAcc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User", "Pass"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbShowAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbShowAccMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbShowAcc);

        btFillTable.setText("Fill");
        btFillTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFillTableActionPerformed(evt);
            }
        });

        cbLuuThongTin.setText("Lưu thông tin");

        buttonGroup1.add(rdNam);
        rdNam.setText("Nam");

        buttonGroup1.add(rdNu);
        rdNu.setText("Nữ");

        btShowGender.setText("Click");
        btShowGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btShowGenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(lbDangNhap)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbbSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnShow)
                                .addGap(67, 67, 67)
                                .addComponent(lbShowPass, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_DangNhap)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_LamMoi)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbLuuThongTin)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnThem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_SieuThoat)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btFillTable))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfUserName)
                            .addComponent(tfPassWord, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rdNu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addComponent(btShowGender))
                            .addComponent(rdNam)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbDangNhap)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(tfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbLuuThongTin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdNam)
                        .addGap(18, 18, 18)
                        .addComponent(rdNu)
                        .addGap(58, 58, 58))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btShowGender)
                        .addGap(70, 70, 70)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_DangNhap)
                    .addComponent(btn_LamMoi)
                    .addComponent(btnThem)
                    .addComponent(btn_SieuThoat))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShow)
                    .addComponent(lbShowPass))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btFillTable)
                        .addGap(262, 262, 262))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showPass() {
        int viTri = cbbSinhVien.getSelectedIndex();
        String acc = listSV.get(viTri).getPassWord();
        lbShowPass.setText(acc);
    }

    public void loadData() {
        listSV.add(new SinhVien("minh", "123", "IT16303"));
        listSV.add(new SinhVien("111", "123", "IT16303"));
        listSV.add(new SinhVien("222", "123", "IT16303"));
        listSV.add(new SinhVien("333", "123", "IT16303"));
        //
    }

    public void clearForm() {
        tfUserName.setText("");
        tfPassWord.setText("");
    }

    public boolean checkTrung(String acc) {
        boolean check = false;
        for (int i = 0; i < listSV.size(); i++) {
            if (listSV.get(i).getUserName().equals(acc)) {
                check = true;
            }
        }
        return check;
    }

    public void addACC() {
        String name = tfUserName.getText();
        String pass = tfPassWord.getText();
        try {
            if (checkTrung(name) == true) {
                JOptionPane.showMessageDialog(rootPane, "Trùng mã rồi thánh ơi");
                return;
            }
        } catch (Exception e) {
        }
        listSV.add(new SinhVien(name, pass, ""));
        cbbSinhVien.addItem(name);
    }

    public void fillTable() {

        DefaultTableModel model = (DefaultTableModel) tbShowAcc.getModel();// lấy model tự tạo từ table
        model.setRowCount(0);// xóa hết dữ liệu 

        for (SinhVien xxx : listSV) {
            model.addRow(new Object[]{xxx.getUserName(), xxx.getPassWord()});
        }

    }

    public void loginForm() {
        try {
            for (SinhVien xxx : listSV) {
                if (tfUserName.getText().equalsIgnoreCase(xxx.getUserName())
                        && tfPassWord.getText().equalsIgnoreCase(xxx.getPassWord())) {
                    JOptionPane.showMessageDialog(rootPane, "Login thành con nhà bà công");
                    return;
                }
            }
            if (tfUserName.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "User không được để trống!");
            } else if (tfPassWord.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Pass không được để trống!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Thất con bà bại");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi login");
        }
    }

    private void btn_SieuThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SieuThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_SieuThoatActionPerformed

    private void btn_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiActionPerformed
        // TODO add your handling code here:
        clearForm();
        cbbSinhVien.setSelectedIndex( 0);
    }//GEN-LAST:event_btn_LamMoiActionPerformed

    private void btn_DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangNhapActionPerformed
        // TODO add your handling code here:
        loginForm();
        clearForm();
    }//GEN-LAST:event_btn_DangNhapActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed

        showPass();
    }//GEN-LAST:event_btnShowActionPerformed

    private void cbbSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSinhVienActionPerformed

        showPass();
    }//GEN-LAST:event_cbbSinhVienActionPerformed

    private void cbbSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbSinhVienMouseClicked

//                showPass();

    }//GEN-LAST:event_cbbSinhVienMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (cbLuuThongTin.isSelected() == true) {
            addACC();
            fillTable();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Tích checbox");
            return;
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void btFillTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFillTableActionPerformed

        fillTable();
    }//GEN-LAST:event_btFillTableActionPerformed

    private void btShowGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btShowGenderActionPerformed
        if(rdNam.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "Nam chuẩn");
        }
        if(rdNu.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "Nữ xịn");
        }
    }//GEN-LAST:event_btShowGenderActionPerformed

    private void tbShowAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbShowAccMouseClicked
        int index = tbShowAcc.getSelectedRow();
//        JOptionPane.showMessageDialog(rootPane, index);
        // cách 1: lấy từ table
//        DefaultTableModel model = (DefaultTableModel) tbShowAcc.getModel();
//        tfUserName.setText(model.getValueAt(index, 0).toString());
//        lbShowPass.setText(model.getValueAt(index, 1).toString());
        // cách 2: lấy từ list
        SinhVien xxx = listSV.get(index);
        tfUserName.setText(xxx.getUserName());
        tfPassWord.setText(xxx.getPassWord());
    }//GEN-LAST:event_tbShowAccMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFillTable;
    private javax.swing.JButton btShowGender;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btn_DangNhap;
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_SieuThoat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbLuuThongTin;
    private javax.swing.JComboBox<String> cbbSinhVien;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDangNhap;
    private javax.swing.JLabel lbShowPass;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTable tbShowAcc;
    private javax.swing.JPasswordField tfPassWord;
    private javax.swing.JTextField tfUserName;
    // End of variables declaration//GEN-END:variables
}
