/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Demo5;

import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class UD1 extends javax.swing.JFrame {

    List<SinhVien> listSV = new ArrayList<>();
    int vitri;
    DefaultTableModel model = new DefaultTableModel();

    public UD1() {
        initComponents();
        setLocationRelativeTo(null);
        model = (DefaultTableModel) tblSinhvien.getModel();

//        listSV.add(new SinhVien("PH01001", "Minh", "Code", 10));
//        listSV.add(new SinhVien("PH01002", "Khanh An", "Code", 10));
//        listSV.add(new SinhVien("PH01005", "Quang Duc", "Code", 10));
//        addTable();
//        if (listSV.size() >= 1) {
//            vitri = 0;
//            display(vitri);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfMasv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfHoten = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfDiem = new javax.swing.JTextField();
        btnDau = new javax.swing.JButton();
        btnTruoc = new javax.swing.JButton();
        lblHienTai = new javax.swing.JLabel();
        btnSau = new javax.swing.JButton();
        btnCuoi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSinhvien = new javax.swing.JTable();
        btnNew = new javax.swing.JButton();
        btThem = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        lbKyNang = new javax.swing.JLabel();
        cbbKyNang = new javax.swing.JComboBox<>();
        btCapNhat = new javax.swing.JButton();
        cbThieuTien = new javax.swing.JCheckBox();
        cbThieuTinh = new javax.swing.JCheckBox();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        btOpenFile = new javax.swing.JButton();
        btLuuFile = new javax.swing.JButton();
        btSXTen = new javax.swing.JButton();
        btSXDiem = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QLSV");

        jLabel2.setText("Mã mèo:");

        jLabel3.setText("Họ văn tèn:");

        jLabel4.setText("Điểm giả:");

        btnDau.setText("|<");
        btnDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDauActionPerformed(evt);
            }
        });

        btnTruoc.setText("<<");
        btnTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruocActionPerformed(evt);
            }
        });

        lblHienTai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHienTai.setText("...");

        btnSau.setText(">>");
        btnSau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSauActionPerformed(evt);
            }
        });

        btnCuoi.setText(">|");
        btnCuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuoiActionPerformed(evt);
            }
        });

        tblSinhvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Mark", "Skill"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSinhvien.setRowHeight(25);
        tblSinhvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSinhvienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSinhvien);

        btnNew.setText("Làm mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btXoa.setText("Xoá");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        lbKyNang.setText("Kỹ năng:");

        cbbKyNang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Code", "Ngủ", "Online", "Type" }));

        btCapNhat.setText("Cập Nhật");
        btCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapNhatActionPerformed(evt);
            }
        });

        cbThieuTien.setText("Thiếu tiền");

        cbThieuTinh.setText("Thiếu tình");

        rdNam.setText("Nam");

        rdNu.setText("Nữ");

        btOpenFile.setText("Open file");
        btOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOpenFileActionPerformed(evt);
            }
        });

        btLuuFile.setText("Lưu file");
        btLuuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLuuFileActionPerformed(evt);
            }
        });

        btSXTen.setText("SX Tên");
        btSXTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSXTenActionPerformed(evt);
            }
        });

        btSXDiem.setText("SX Điểm");
        btSXDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSXDiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfMasv, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbKyNang)
                                        .addGap(42, 42, 42)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfDiem, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(cbbKyNang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btLuuFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btOpenFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btSXTen, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbThieuTinh)
                                    .addComponent(cbThieuTien)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btSXDiem))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(205, 205, 205)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdNu)
                                            .addComponent(rdNam))))
                                .addGap(0, 59, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnDau)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnTruoc)
                                    .addGap(2, 2, 2)
                                    .addComponent(lblHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnSau)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnCuoi))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(173, 173, 173)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMasv, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnNew)
                                .addComponent(btOpenFile)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btLuuFile))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSXTen)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(cbThieuTien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbThieuTinh)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbKyNang)
                    .addComponent(cbbKyNang)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addComponent(btSXDiem)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDau, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTruoc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHienTai)
                            .addComponent(btnSau, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(rdNam)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdNu))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnNew, jLabel2, tfMasv});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnTruoc, lblHienTai});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//
    private void display(int vitri) {
        if (vitri >= 0) {
//      SinhVien sv = listSV.get(vitri);
            tfMasv.setText(listSV.get(vitri).getMasv());
            tfHoten.setText(listSV.get(vitri).getHoten());
            tfDiem.setText(listSV.get(vitri).getDiem() + "");
            lblHienTai.setText((vitri + 1) + " of " + listSV.size());
            cbbKyNang.setSelectedItem(listSV.get(vitri).getKyNang());
            tblSinhvien.setRowSelectionInterval(vitri, vitri);//Table chon dong tuong ung 
        } else {
            lblHienTai.setText("...");
        }
    }

    private void addTable() {

        model.setRowCount(0);//xoa toan bo du lieu cua Model
        for (SinhVien x : listSV) {
            model.addRow(new Object[]{x.getMasv(), x.getHoten(), x.getDiem(), x.getKyNang()});
        }
        if (model.getRowCount() > 0) {//Table co du lieu
            tblSinhvien.setRowSelectionInterval(0, 0);//Cho Table chon dong dau tien
        }

    }

    private void clearForm() {
        tfMasv.setText("");
        tfHoten.setText("");
        tfDiem.setText("");
        cbbKyNang.setSelectedIndex(0);
        vitri = -1;
        lblHienTai.setText("...");
    }

    public boolean checkMSSV(String a) {
        boolean check = false;
        for (int i = 0; i < listSV.size(); i++) {
            if (listSV.get(i).getMasv().equals(tfMasv.getText())) {
                check = true;
            }
        }
        return check;
    }

    private void addList() {
        // lấy đc dữ liệu từ textfiel -> thêm vào list
        SinhVien sv = new SinhVien();
        try {
            if (checkMSSV(tfMasv.getText()) == true) {
                JOptionPane.showMessageDialog(this, "Mã sinh viên đã tồn tại");
                return;
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi" + ex);
        }
        try {
            if (tfMasv.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "MSSV không được để trống");
                return;
            } else {
                sv.setMasv(tfMasv.getText());// lấy dữ liệu tại text-> gán cho sv
            }
        } catch (Exception e) {
            e.printStackTrace();
//            JOptionPane.showMessageDialog(this, "Lỗi" + e);
        }
        try {
            if (tfHoten.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "Tên không được để trống");
                return;
            } else {
                sv.setHoten(tfHoten.getText());// lấy dữ liệu tại text-> gán cho sv
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi" + e);
        }
        try {
            if (tfDiem.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "Điểm không được để trống");
                return;
            } else {
                sv.setDiem(Double.parseDouble(tfDiem.getText()));// lấy dữ liệu tại text-> gán cho sv
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi" + e);
        }
        String kyNang = (String) cbbKyNang.getSelectedItem();
        sv.setKyNang(kyNang);

        listSV.add(sv);

    }

    private void xoaList() {
        try {
            int index = tblSinhvien.getSelectedRow();
            listSV.remove(index);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ban vui long chon SV tren Table");
        }

    }

    private void capNhat() {
        try {
            if (vitri >= 0) {
                //Cap nhat trong list
                String hoten = tfHoten.getText();
                String masv = tfMasv.getText();
                double diem = Double.parseDouble(tfDiem.getText());
                String kyNang = cbbKyNang.getSelectedItem().toString();

                SinhVien sv = new SinhVien(masv, hoten, kyNang, diem);
                //Cap nhat tren list
                listSV.set(vitri, sv);
                //Cap nhat tren form
                display(vitri);

                //cap nhat trong table
                model.setValueAt(masv, vitri, 0);
                model.setValueAt(hoten, vitri, 1);
                model.setValueAt(diem, vitri, 2);
                model.setValueAt(sv.getKyNang(), vitri, 3);

            } else {
                JOptionPane.showMessageDialog(this, "Ban vui long chon SV tren Table");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gap loi khi sua");
        }

    }
    
    
    private void btnDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDauActionPerformed
        vitri = 0;
        display(vitri);
    }//GEN-LAST:event_btnDauActionPerformed

    private void btnCuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuoiActionPerformed
        vitri = listSV.size() - 1;
        display(vitri);
    }//GEN-LAST:event_btnCuoiActionPerformed

    private void btnTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruocActionPerformed
        if (vitri > 0) {
            vitri--;
            display(vitri);
        }
    }//GEN-LAST:event_btnTruocActionPerformed

    private void btnSauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSauActionPerformed
        if (vitri < listSV.size() - 1) {
            vitri++;
            display(vitri);
        }
    }//GEN-LAST:event_btnSauActionPerformed

    private void tblSinhvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSinhvienMouseClicked
        int row = tblSinhvien.getSelectedRow();

        if (row >= 0) {
            vitri = row;
            display(vitri);
        }


    }//GEN-LAST:event_tblSinhvienMouseClicked
    public void openFile() {
        File file = new File("1530BBB.txt");
        listSV = (List<SinhVien>) IOData.readOb("1530BBB.txt");
    }
    public void saveFile() {
        IOData.writeOb("1530BBB.txt", listSV);
    }
    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        clearForm();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        addList();
        addTable();

    }//GEN-LAST:event_btThemActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        xoaList();
        addTable();

    }//GEN-LAST:event_btXoaActionPerformed

    private void btCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapNhatActionPerformed

        capNhat();
    }//GEN-LAST:event_btCapNhatActionPerformed

    private void btSXTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSXTenActionPerformed
        Collections.sort(listSV ,(a,b) -> a.getHoten().compareTo(b.getHoten()) );
        addTable();
    }//GEN-LAST:event_btSXTenActionPerformed

    private void btSXDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSXDiemActionPerformed
        Collections.sort(listSV ,(a,b) -> (int)(a.getDiem() - b.getDiem()) );
        addTable();
    }//GEN-LAST:event_btSXDiemActionPerformed

    private void btOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOpenFileActionPerformed
         try {
            this.openFile();
            if (listSV.size() > 0) {
                addTable();
                vitri = 0;
                display(vitri);
                tblSinhvien.setRowSelectionInterval(vitri, vitri);
            } else {
                vitri = -100;
                this.clearForm();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btOpenFileActionPerformed

    private void btLuuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLuuFileActionPerformed
        int luaChon = JOptionPane.showConfirmDialog(this, "Bạn muốn lưu hay không?",
                "Hỏi đáp lưu file", JOptionPane.YES_NO_OPTION,
                JOptionPane.YES_NO_OPTION);
        try {
            if (luaChon == JOptionPane.YES_OPTION) {
                this.saveFile();
            } else {
                return;
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btLuuFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UD1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UD1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UD1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UD1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UD1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCapNhat;
    private javax.swing.JButton btLuuFile;
    private javax.swing.JButton btOpenFile;
    private javax.swing.JButton btSXDiem;
    private javax.swing.JButton btSXTen;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btXoa;
    private javax.swing.JButton btnCuoi;
    private javax.swing.JButton btnDau;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSau;
    private javax.swing.JButton btnTruoc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbThieuTien;
    private javax.swing.JCheckBox cbThieuTinh;
    private javax.swing.JComboBox<String> cbbKyNang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbKyNang;
    private javax.swing.JLabel lblHienTai;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTable tblSinhvien;
    private javax.swing.JTextField tfDiem;
    private javax.swing.JTextField tfHoten;
    private javax.swing.JTextField tfMasv;
    // End of variables declaration//GEN-END:variables

}
